#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>
#include "glwidget.h"

class View;

namespace Ui {
    class MainWindow;
}

class DataBinding;

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();
    void dataBind();

private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *m_ui;
    QList<DataBinding*> m_bindings;
    GLWidget *m_glWidget;

public slots:
    void settingsChanged();
    void throwSnowball();
};

#endif // MAINWINDOW_H
